#!/bin/sh

# Autostart
sxhkd &
$HOME/.config/scripts/start_polybar &
nm-applet &
compton -cC &
hsetroot -solid "#2E3440" &

# If refreshing bspwm, remove rules to prevent doubling up
bspc rule -r "*"

# Start workspaces on the monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Configuration
bspc config border_width            0
bspc config window_gap              10
bspc config top_padding             30   # polybar's height
bspc config focus_follows_pointer   true

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true


