#!/bin/bash
get_icon(){
    case $1 in
        Playing) icon="";;
        Paused)  icon="";;
        *)       icon="";
    esac
    
    echo "   $icon   "
}


cat <(get_icon $(playerctl status)) <(playerctl metadata --format "{{ artist }} - {{ title }}") | tr "\n" " "
