#!/bin/bash
get_icon(){
    case $1 in
        Playing) icon="";;
        Paused)  icon="";;
        *)       icon="";
    esac
    
    echo "   $icon  "
}


cat <(get_icon $(playerctl status)) <(playerctl metadata --format "{{ artist }} - {{ title }}") <(playerctl position --format "({{ duration(position) }}/") <(playerctl metadata --format "{{ duration(mpris:length) }})") | tr "\n" " "
